# Ce flux de travail effectuera une installation propre des dépendances de node, les mettra en cache/les restaurera, 
# construira le code source et exécutera les tests sur différentes versions de node.
# Pour plus d'informations, consultez : https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI avec Redis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    # Définition du service Redis
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --save ""

    steps:
    - uses: actions/checkout@v2
    - name: Utiliser Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
